version: "3.9"
services:
  app:
    build: .  # Build the image from the current directory
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - .:/app  # Mount the current directory into the container
    ports:
      - "8000:8000"  # Map the container's port to the host
    # environment:
    #   - PYTHONUNBUFFERED=1  # Disable buffering of Python output
    # command: pdm run uvicorn main:app --host 0.0.0.0 --port 8000
    command: pdm run uvicorn src.kollikissa.main:app --host 0.0.0.0 --port 8000 --reload